name: haha-this-is-empty:D
top_k: 1
question_key: question
gt_key: answer
page_id_key: page_ids
truncate_len: null
max_page: 1000
max_character_per_page: 100000
use_mix: false
r_text_key: "text-top-10-question"
r_image_key: "image-top-10-question"
r_mix_key: ${retrieval.r_mix_key}
data_dir: ./data/${dataset.name}
result_dir: ./results/${dataset.name}/${run-name}
extract_path: ./tmp/${dataset.name}
document_path: ./data/${dataset.name}/documents
sample_path: ${dataset.data_dir}/samples_retrieval_dag.json
sample_with_retrieval_path: ${dataset.data_dir}/sample_retrieval_dag_final.json